# disable dispays have seperate spaces
# defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse window-force-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 14
inner.vertical =   14
outer.left =       14
outer.bottom =     14
outer.top =        14
outer.right =      14

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented


[mode.main.binding]
ctrl-alt-cmd-m = 'mode main'
ctrl-alt-cmd-slash = 'mode service'
ctrl-alt-cmd-1 = 'mode tiled'
ctrl-alt-cmd-2 = 'mode stacked'

ctrl-alt-cmd-v = ['layout tiles horizontal vertical', 'mode tiled']
ctrl-alt-cmd-space = ['layout accordion horizontal vertical', 'mode stacked']

#swap windows
#change workspace

ctrl-alt-cmd-shift-minus = 'resize smart -50'
ctrl-alt-cmd-shift-equal = 'resize smart +50'

ctrl-alt-cmd-s = 'workspace-back-and-forth'
ctrl-alt-cmd-shift-d = 'move-workspace-to-monitor --wrap-around next'


# 'service' binding mode declaration.
[mode.service.binding]
esc = ['reload-config', 'mode main']
e = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

ctrl-alt-cmd-shift-h = ['join-with left', 'mode main']
ctrl-alt-cmd-shift-j = ['join-with down', 'mode main']
ctrl-alt-cmd-shift-k = ['join-with up', 'mode main']
ctrl-alt-cmd-shift-l = ['join-with right', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'


[mode.tiled.binding]

ctrl-alt-cmd-h = 'focus left'
ctrl-alt-cmd-j = 'focus down'
ctrl-alt-cmd-k = 'focus up'
ctrl-alt-cmd-l = 'focus right'

#swap
ctrl-alt-cmd-shift-h = 'move left'
ctrl-alt-cmd-shift-j = 'move down'
ctrl-alt-cmd-shift-k = 'move up'
ctrl-alt-cmd-shift-l = 'move right'

ctrl-alt-cmd-space = ['layout h_accordion', 'mode stacked']
ctrl-alt-cmd-shift-slash = 'mode service'


[mode.stacked.binding]

ctrl-alt-cmd-i = 'focus left'
ctrl-alt-cmd-o = 'focus right'
ctrl-alt-cmd-h = 'workspace prev'
ctrl-alt-cmd-l = 'workspace next'

#swap
ctrl-alt-cmd-shift-h = 'move left'
ctrl-alt-cmd-shift-j = 'move down'
ctrl-alt-cmd-shift-k = 'move up'
ctrl-alt-cmd-shift-l = 'move right'

ctrl-alt-cmd-space =  ['layout h_tiles ', 'mode tiled']
ctrl-alt-cmd-shift-slash = 'mode service'
