
# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = ['layout h_accordion', 'mode stacked', 'exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
on-focused-monitor-changed = ['move-mouse monitor-force-center']
on-focus-changed = ['move-mouse window-force-center']
# Hier festlegen, dass bei workspace change geguckt werden soll, ob das layout stacked oder tiled ist
#on-event = ['mode stacked/tiled']


# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

[gaps]
inner.horizontal = 14
inner.vertical =   14
outer.left =       14
outer.bottom =     14
outer.top =        [{ monitor.main = 16 }, { monitor.C34H89x = 48 }, { monitor."BenQ GW2765"= 52 }, 24]
outer.right =      14

# 'main' binding mode declaration
# 'main' binding mode must be always presented

[mode.main.binding]
ctrl-alt-cmd-space = ['layout h_accordion', 'mode stacked']
ctrl-alt-cmd-slash = 'mode service'


[mode.tiled.binding]
ctrl-alt-cmd-h = 'focus --boundaries-action stop left'
ctrl-alt-cmd-j = 'focus down'
ctrl-alt-cmd-k = 'focus up'
ctrl-alt-cmd-l = 'focus --boundaries-action stop right'

#swap, soon with || operator for send to next screen - before that use transform mode
ctrl-alt-cmd-shift-h = 'move left'
ctrl-alt-cmd-shift-j = 'move down'
ctrl-alt-cmd-shift-k = 'move up'
ctrl-alt-cmd-shift-l = 'move right'

#to escape the space because super h/l is used for focus
ctrl-alt-cmd-s = ['workspace-back-and-forth', 'mode stacked']

ctrl-alt-cmd-i = ['resize smart -50', 'mode tiled']
ctrl-alt-cmd-o = ['resize smart +50', 'mode tiled']


#to return to all modes
ctrl-alt-cmd-slash = 'mode service'
ctrl-alt-cmd-space = ['layout h_accordion', 'mode stacked']

[mode.stacked.binding]
ctrl-alt-cmd-i = 'focus --boundaries-action stop left'
ctrl-alt-cmd-o = 'focus --boundaries-action stop right'
# when I end up in an tiled workspace the keybindings are still stack mode 
# I need to restart (exec?) each time I jump to next workspace
ctrl-alt-cmd-h = ['workspace prev']
ctrl-alt-cmd-j = ['focus-monitor down', 'mode stacked']
ctrl-alt-cmd-k = ['focus-monitor up', 'mode stacked']
ctrl-alt-cmd-l = ['workspace next']

#swap, soon with || operator for send to next screen - before that use transform mode
ctrl-alt-cmd-shift-h = 'move left'
ctrl-alt-cmd-shift-j = 'move down'
ctrl-alt-cmd-shift-k = 'move up'
ctrl-alt-cmd-shift-l = 'move right'

#to escape the space because super h/l is used for focus
ctrl-alt-cmd-s = ['workspace-back-and-forth', 'mode tiled']

#to return to all modes
ctrl-alt-cmd-slash = 'mode service'
ctrl-alt-cmd-space = ['layout h_tiles', 'mode tiled']

[mode.transform.binding]
# I should alwways send all to next workspace so I dont fuck up my stack/tile mode (instead of joining)
h = ['move-node-to-workspace --wrap-around prev', 'workspace prev', 'mode stacked']
j = ['move-node-to-monitor down', 'focus-monitor --wrap-around next', 'mode stacked']
k = ['move-node-to-monitor up', 'focus-monitor --wrap-around next', 'mode stacked']
l = ['move-node-to-workspace --wrap-around next', 'workspace next', 'mode stacked']

s = ['move-workspace-to-monitor --wrap-around next','focus-monitor --wrap-around next', 'mode stacked']

shift-h = ['move-node-to-monitor left', 'mode stacked']
shift-j = ['move-node-to-monitor down', 'mode stacked']
shift-k = ['move-node-to-monitor up', 'mode stacked']
shift-l = ['move-node-to-monitor right', 'mode stacked']

#to return to all modes
ctrl-alt-cmd-slash = 'mode service'


[mode.service.binding]

r = ['reload-config', 'mode stacked']
e = ['flatten-workspace-tree', 'mode stacked'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode stacked'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode stacked']

#to return to all modes
m = 'mode main'
t = 'mode tiled'
s = 'mode stacked'
enter = 'mode transform'

alt-1 = ['workspace 1', 'mode stacked']
alt-2 = ['workspace 2', 'mode stacked']
alt-3 = ['workspace 3', 'mode stacked']
alt-4 = ['workspace 4', 'mode stacked']


