  # ============================================================================
  # Raycast Snippets (imported)
  # ============================================================================

  # Kontakt
  - trigger: "?A"
    replace: "Vitus Pacholleck \nBodenbacher Straße 30\n01277 Dresden"

  - trigger: "?tu"
    replace: "vitus.pacholleck@mailbox.tu-dresden.de"

  - trigger: "?vp"
    replace: "vituspach@gmail.com"

  - trigger: "?wb"
    replace: "vitus.pacholleck@wandelbots.com"

  - trigger: "?op"
    replace: "theorbitproduction@gmail.com"

  - trigger: "vipa"
    replace: "Vitus Pacholleck"

  - trigger: "vilipa"
    replace: "Vitus-Lion Pacholleck"

  # Datum (Espanso format)
  - trigger: "?D"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Anführungszeichen mit Cursor
  - trigger: ",,"
    replace: "„$|$""

  # Text Bausteine
  - trigger: "ue5"
    replace: "Unreal Engine 5"

  - trigger: "sgf"
    replace: "Sehr geehrte Frau"

  - trigger: "sgh"
    replace: "Sehr geehrter Herr"

  - trigger: "vg"
    replace: "Viele Grüße,\nVitus Pacholleck"

  - trigger: "lg"
    replace: "Liebe Grüße,\nVitus"

  # Code & Dev
  - trigger: "?W"
    replace: "```\n{{clipboard}}\n```"
    vars:
      - name: clipboard
        type: clipboard

  - trigger: "?C"
    replace: "%s/$|$//gc"

  - trigger: "??"
    replace: "\"- [ ]\""

  - trigger: "-->"
    replace: "→ "

  - trigger: "?*"
    replace: "%s/\\*\\*//g"

  - trigger: "?N"
    replace: "Schau hier #file:wandelbots-nova und 'github_repo' https://github.com/wandelbotsgmbh/wandelbots-nova. Nur Syntax verwenden, den es gibt."
