# =============================================================================
# Abbreviations
# =============================================================================
# Central source for shell abbreviations across all systems
# Used by templates to generate zsh-abbr, PowerShell, etc.

abbreviations:
  # ---------------------------------------------------------------------------
  # Universal - all systems
  # ---------------------------------------------------------------------------
  universal:
    c: "chezmoi"
    ca: "chezmoi apply -v"
    gc: "git checkout"
    l: "lazygit"
    p: "uv run python"
    s: "serie"
    "..": "cd .."
    "...": "cd ../.."

  # ---------------------------------------------------------------------------
  # macOS only
  # ---------------------------------------------------------------------------
  darwin:
    da: "~/Documents/obsidian/Diplomarbeit/scripts/build.sh"
    backup: "restic -r /Volumes/TOSHIBA\\ EXT/restic-for-t7 --verbose backup /Volumes/T7\\ Shield"
    bi: "brew install"
    bs: "brew search"
    bu: "brew uninstall"
    up: "brew upgrade"
    copyid: "nova config view 2>&1 | tee >(awk '/^virtualid:/ {print $2}' | pbcopy)"
    copyip: "nova config view 2>&1 | tee >(awk '/^host:/ {print $2}' | pbcopy)"
    f: "fzf | pbcopy"
    rl: "source ~/.zshrc"
    v: "source .venv/bin/activate"

  # ---------------------------------------------------------------------------
  # Windows only
  # ---------------------------------------------------------------------------
  windows:
    ahk: 'Get-Process | Where-Object {$_.Name -like "*AutoHotkey*"} | Stop-Process -Force; Start-Process "c:\Users\Vitus\wotfiles\ahkv1\macish.ahk"'
    f: "fzf | clip.exe"
    ov: "A:\\isaac-sim\\isaac-sim.bat"
    rl: ". $PROFILE"
    v: ".venv\\Scripts\\Activate.ps1"

  # ---------------------------------------------------------------------------
  # Linux only
  # ---------------------------------------------------------------------------
  linux:
    f: "fzf | wl-copy"
    rl: "source ~/.zshrc"
    v: "source .venv/bin/activate"

# =============================================================================
# Shared App Paths
# =============================================================================
# Defines where shared configs should be deployed per OS
# Paths are relative to $HOME (or %USERPROFILE% on Windows)

shared_apps:
  vscode:
    source: "shared/vscode"
    target:
      darwin: "Library/Application Support/Code/User"
      linux: ".config/Code/User"
      windows: "AppData/Roaming/Code/User"
    files:
      - { src: "settings.json.tmpl", dst: "settings.json", template: true }
      - {
          src: "keybindings.json.tmpl",
          dst: "keybindings.json",
          template: true,
        }
      - { src: "custom-vscode.css", dst: "custom-vscode.css", template: false }

  zed:
    source: "shared/zed"
    target:
      darwin: ".config/zed"
      linux: ".config/zed"
      windows: "AppData/Roaming/Zed"
    files:
      - { src: "keymap.json.tmpl", dst: "keymap.json", template: true }
      - { src: "private_settings.json", dst: "settings.json", template: false }

  nvim:
    source: "shared/nvim"
    target:
      darwin: ".config/nvim"
      linux: ".config/nvim"
      windows: "AppData/Local/nvim"
    files:
      - { src: "init.vim.tmpl", dst: "init.vim", template: true }

  lf:
    source: "shared/lf"
    target:
      darwin: ".config/lf"
      linux: ".config/lf"
      windows: "AppData/Roaming/lf"
    files:
      - { src: "lfrc.tmpl", dst: "lfrc", template: true }
    # OS-specific files handled separately in scripts (preview.sh vs preview.cmd)
    files_darwin:
      - { src: "preview.sh", dst: "preview.sh", executable: true }
      - { src: "cleaner.sh", dst: "cleaner.sh", executable: true }
    files_linux:
      - { src: "preview.sh", dst: "preview.sh", executable: true }
      - { src: "cleaner.sh", dst: "cleaner.sh", executable: true }
    files_windows:
      - { src: "preview.cmd", dst: "preview.cmd" }

  zen:
    source: "shared/zen"
    target:
      darwin: "Library/Application Support/zen/policies"
    files:
      - { src: "policies.json", dst: "policies.json", template: false }

# =============================================================================
# Special Apps (non-standard deployment)
# =============================================================================
# These require special handling and are not part of the generic loop

special_apps:
  # Zen on Windows needs special handling (app path varies: LOCALAPPDATA, Scoop, etc.)
  # On macOS/Linux, zen is handled as a regular shared_app above
  zen:
    source: "shared/zen"
    files:
      - { src: "policies.json", dst: "policies.json" }
    restart_after: true
