# =============================================================================
# Abbreviations
# =============================================================================
# Central source for shell abbreviations across all systems
# Used by templates to generate zsh-abbr, PowerShell, etc.

abbreviations:
  # ---------------------------------------------------------------------------
  # Universal - all systems
  # ---------------------------------------------------------------------------
  universal:
    c: "chezmoi"
    ca: "chezmoi apply"
    da: "cd $HOME/Documents/obsidian/Diplomarbeit && just build"
    go: "git checkout"
    p: "git pull"
    P: "git push"
    ga: "git add -A"
    gc: "git commit -m"
    g: "git"
    l: "lazygit"
    py: "uv run python"
    s: "serie"
    "..": "cd .."
    "...": "cd ../.."

  # ---------------------------------------------------------------------------
  # macOS only
  # ---------------------------------------------------------------------------
  darwin:
    backup: "restic -r /Volumes/TOSHIBA\\ EXT/restic-for-t7 --verbose backup /Volumes/T7\\ Shield"
    bi: "brew install"
    bs: "brew search"
    bu: "brew uninstall"
    bup: "brew upgrade"
    bl: "brew list"
    copyid: "nova config view 2>&1 | tee >(awk '/^virtualid:/ {print $2}' | pbcopy)"
    copyip: "nova config view 2>&1 | tee >(awk '/^host:/ {print $2}' | pbcopy)"
    f: "fzf | pbcopy"
    rl: "source ~/.zshrc"
    v: "source .venv/bin/activate"
    usdview: "PYTHONPATH=/opt/local/USD/lib/python PATH=/opt/local/USD/bin:$PATH python3.11 /opt/local/USD/bin/usdview"

  # ---------------------------------------------------------------------------
  # Windows}} only
  # ---------------------------------------------------------------------------
  windows:
    ahk: 'Get-Process | Where-Object {$_.Name -like "*AutoHotkey*"} | Stop-Process -Force; Start-Process "C:\Users\Vitus\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\macish.ahk"'
    f: "fzf | clip.exe"
    ov: "A:\\isaac-sim\\isaac-sim.bat"
    rl: ". $PROFILE"
    v: ".venv\\Scripts\\Activate.ps1"
    ws: "winget search"
    wi: "winget install"
    wu: "winget uninstall"
    wup: "winget update"
    wl: "winget list"
    ss: "scoop-search"
    si: "scoop install"
    su: "scoop uninstall"
    sup: "scoop update"
    sl: "scoop list"

  # ---------------------------------------------------------------------------
  # Linux only
  # ---------------------------------------------------------------------------
  linux:
    f: "fzf | wl-copy"
    rl: "source ~/.zshrc"
    v: "source .venv/bin/activate"

# =============================================================================
# Shared App Paths
# =============================================================================
# Defines where shared configs should be deployed per OS
# Paths are relative to $HOME (or %USERPROFILE% on Windows)

shared_apps:
  vscode:
    source: "shared/vscode"
    target:
      darwin: "Library/Application Support/Code/User"
      linux: ".config/Code/User"
      windows: "AppData/Roaming/Code/User"
    files:
      - { src: "settings.json.tmpl", dst: "settings.json", template: true }
      - {
          src: "keybindings.json.tmpl",
          dst: "keybindings.json",
          template: true,
        }
      - { src: "custom-vscode.css", dst: "custom-vscode.css", template: false }

  zed:
    source: "shared/zed"
    target:
      darwin: ".config/zed"
      linux: ".config/zed"
      windows: "AppData/Roaming/Zed"
    files:
      - { src: "keymap.json.tmpl", dst: "keymap.json", template: true }
      - { src: "private_settings.json", dst: "settings.json", template: false }

  nvim:
    source: "shared/nvim"
    target:
      darwin: ".config/nvim"
      linux: ".config/nvim"
      windows: "AppData/Local/nvim"
    files:
      - { src: "init.vim.tmpl", dst: "init.vim", template: true }

  lf:
    source: "shared/lf"
    target:
      darwin: ".config/lf"
      linux: ".config/lf"
      windows: "AppData/Roaming/lf"
    files:
      - { src: "lfrc.tmpl", dst: "lfrc", template: true }
    # OS-specific files handled separately in scripts (preview.sh vs preview.cmd)
    files_darwin:
      - { src: "preview.sh", dst: "preview.sh", executable: true }
      - { src: "cleaner.sh", dst: "cleaner.sh", executable: true }
    files_linux:
      - { src: "preview.sh", dst: "preview.sh", executable: true }
      - { src: "cleaner.sh", dst: "cleaner.sh", executable: true }
    files_windows:
      - { src: "preview.cmd", dst: "preview.cmd" }

# =============================================================================
# Special Apps (non-standard deployment)
# =============================================================================
# These require special handling and are not part of the generic loop

special_apps:
  # Zen needs special handling on both macOS and Windows:
  # - macOS: deploys into app bundle + re-signing
  # - Windows: app path varies (LOCALAPPDATA, Scoop, etc.)
  zen:
    source: "shared/zen"
    files:
      - { src: "policies.json", dst: "policies.json" }
    restart_after: true
