#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

# Bar Appearance
bar=(
  position=top
  height=25
  blur_radius=30
  color=$TRANSPARENT
  corner_radius=8
  y_offset=10
  margin=-9
)
sketchybar --bar "${bar[@]}"

#default settings for shown items
default=(
  padding_left=5
  padding_right=5
  icon.font="SF Symbols:Bold:15.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# previously: icon="$sid"
# Aerospace Workspace Indicators
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    \
    background.corner_radius=8 \
    \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/as_space.sh $sid"
done

# Left Items
source $ITEM_DIR/front_app.sh

# Right Items
source $ITEM_DIR/mic_status.sh
source $ITEM_DIR/clock.sh
source $ITEM_DIR/pomodoro.sh
#sketchybar --add alias kindaVim right --set kindaVim y_offset=-1

# autoupdate when saving the file
sketchybar --hotload on

# Force all scripts to run the first time (never do this in a script)
sketchybar --update

#sketchybar --add item test left \
#  --set test icon="test" \
#  --add event hover \
#  --subscribe test hover mouse.entered mouse.exited \
#  script="$PLUGIN_DIR/test.sh"

#source $ITEM_DIR/ms_spaces.sh
#sketchybar --add alias Raycast right
#source $ITEM_DIR/stack.sh
#source $ITEM_DIR/yabai_mode.sh

#dynamic-island-sketchybar

# Mission Control Space Indicators
#SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
#for i in "${!SPACE_ICONS[@]}"
#do
#  sid="$(($i+1))"
#  space=(
#    space="$sid"
#    icon="${SPACE_ICONS[i]}"
#    icon.padding_left=7
#    icon.padding_right=4
#    background.corner_radius=5
#    background.height=25
#    label.drawing=on
#    script="$PLUGIN_DIR/ms_space.sh"
#    click_script="yabai -m space --focus $sid"
#  )
#  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
#done

# aerospace setting
#AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
#AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')
