#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# color previously 0x40000000
sketchybar --bar position=top \
  height=28 \
  blur_radius=30 \
  color=0x00000000 \
  corner_radius=8 \
  y_offset=10\
  margin=-11

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Symbols:Bold:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# color previously 0x40ffffff
# background.color=0x40000000
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=7
    icon.padding_right=4
    background.corner_radius=5
    background.height=25
    label.drawing=on
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####

source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

##### Adding Right Items #####

source $ITEM_DIR/yabai_mode.sh
source $ITEM_DIR/clock.sh
source $ITEM_DIR/stack.sh


# not working yet
# sketchybar --set clock action="/Users/vituspacholleck/.config/sketchybar/plugins/clock.sh mouse.clicked"

# autoupdate when saving the file
sketchybar --hotload on

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
