#!/bin/bash

if [ "$SENDER" = "space_windows_change" ]; then
  space="$(echo "$INFO" | jq -r '.space')"
  apps="$(echo "$INFO" | jq -r '.apps | keys[]')"

  icon_strip=" "
  if [ "${apps}" != "" ]; then
    while read -r app; do
      icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
    done <<<"${apps}"
  else
    icon_strip=" "
  fi

  #code generated by copilot
  active_space=$(yabai -m query --spaces --space | jq -r '.index')

  if [ $space -eq $active_space ]; then
    sketchybar --set space.$space label="$icon_strip" label.highlight=off
  else
    sketchybar --set space.$space label="$icon_strip" label.highlight=on
  fi
fi

