schema_version = "1.0.0"

# Blender Add-on Manifest File
id = "light_wrangler"
version = "2.1.9"
name = "Light Wrangler"
tagline = "Cursor-Targeted Lighting Add-On"
maintainer = "Leonid Altman <contact@leonidaltman.com>"
type = "add-on"

# Permissions your add-on may need
permissions = ["files"]

# Link to documentation or support
website = "https://blendermarket.com/products/light-wrangler/docs"

# Tags to help categorize the add-on
tags = ["Lighting", "Rendering", "3D View"]

# Specify the minimum and maximum supported Blender versions
blender_version_min = "3.0.0"
blender_version_max = "5.2.0"

# License information using SPDX identifier
license = ["SPDX:GPL-3.0-or-later"]


